# Generated by Django 3.2.6 on 2021-08-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('origin_country', models.CharField(max_length=56)),
            ],
        ),
    ]
